core/confiant.go
return empty array and not null
=> fixing confiant get api

modules/slack.go
=> Slack module

validations/factorValidation.go, validations/validation.go
this is a hotfix and should be removed as quick as possible
=> factor are allowed beween 0-20,

api/rest/bulk/dpo.go, api/rest/bulk/floor.go, api/rest/confiant.go, api/rest/configuration_manager.go, api/rest/dpo.go, api/rest/factor.go, api/rest/floor.go, api/rest/pixalate.go, api/rest/publisher_domain.go, core/confiant.go, core/configuration_manager.go, core/dpo_rule.go, core/factor.go, core/floor.go, core/pixalate.go, utils/helpers/helper.go, utils/metadata.go, utils/response.go
1. Change floor metadata rule_id
2. Change floor metadata key and value
3. Change response in order to see also err message from system  in response
=> Floor metadata 

api/rest/floor.go, core/floor.go
Rules without rule_id are invalid. 
We have cases of multiple rules with the same rule_id 
Device is overriding
=> Fix ruleId for floor

api/rest/floor.go, core/floor.go, migrations/008_floor.up.sql, models/floor.go, models/floor_test.go, models/publisher.go
Added new fields
- os
- browser
- placement_type
Also changed migration , now primary key is rule_id
=> Floor add new fields

core/confiant.go, core/dpo_rule.go, core/factor.go, core/floor.go, core/global_factor.go, core/pixalate.go, core/publisher_domain.go, workers/sync/publisher/publisher.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3308/)
1. Field "created_at" will not be updated during upsert operation;
=> [3308] fixed created_at continuously update

core/publisher_details.go, core/publisher_details_test.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3331/)
1. Added extra columns for ordering
=> [3331] updated ordering

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/download.go, cmd/api.go, core/auth.go, core/download.go, core/download_test.go, core/dpo_rule.go, core/pixalate.go, utils/constant/http.go, validations/downloadValidation.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3347/)
1. Added new endpoint ```POST /download```. It helps to download any array of json objects as csv file. Important to note that object should have same structure. Example of body:
```
[
{
"id": 1,
"name": "publisher_1",
"active": true,
"domain": "1.com",
"factor": 0.01,
"account_manager_id": "am_id_1"
},
{
"id": 2,
"name": "publisher_2",
"active": false,
"domain": "2.com",
"factor": 0.05,
"account_manager_id": "am_id_2"
},
{
"id": 3,
"name": "publisher_3",
"active": true,
"domain": "3.com",
"factor": 0.1,
"account_manager_id": "am_id_3"
}
]
```
2. Fixed some small parts in package core. Mostly in string formatting;
=> 3347 Download API

.github/workflows/test.yml, api/rest/blocks_test.go, api/rest/bulk/factor_test.go, api/rest/floor_test.go, bcdb/postgres.go, core/dpo.go, go.mod, go.sum, validations/dpo/dpo_test.go, workers/alerts/factor/factor.go, workers/ansible/inventory/worker.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3353/)
1. Fixed all the tests;
2. Added new workflow which will run for all pushes expect to "main" branch. It will run all the tests in order to make sure that everything is fine;
First run of new workflow - https://github.com/OnlineMediaSolutions/bcwork/actions/runs/11090761680
=> 3353 Fixing tests

workers/sellers/helpers.go, workers/sellers/sellers_test.go
Fix sellers and competitors
1. Delete unused checking for application-json
2. Filter competitor in order to send only data that has historical data in db
=> Fix competitors logic

core/dpo.go, validations/dpo/dpo_test.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3367/)
This PR is a revert of DPO changes which was made in https://github.com/OnlineMediaSolutions/bcwork/pull/146
=> [3367] fixed dpo

api/rest/targeting_test.go, utils/constant/targeting.go, validations/validation.go
Vlad ask for small changes - Capitalize names of statuses because this naming has already used in publishers
=> [3363] capitalized names of statuses

core/targeting.go, core/targeting_test.go
Now daily_cap will not be updated everytime. Only when it changed.
=> [3363] fixed daily_cap processing

workers/test_api/cases.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3392)
=> [3392] updated factor get test case

api/rest/floor_test.go, core/factor.go, core/floor.go
1. Add factor rule_id to response
2. Add floor rule_id to response
=> Add rule_id to response feed

modules/supertokens/middlewares.go
Using different code for disabled users
=> changed session verification response codes

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/search_test.go, core/search.go, dto/search.go, dto/search_test.go, migrations/022_search_view.up.sql, models/history_test.go, models/search_view.go
1. removed search for demand_partner_name; 
2. added sorting to search results;
=> [3092] search changes

api/rest/blocks_test.go, api/rest/bulk_dpo_test.go, api/rest/bulk_factor_test.go, api/rest/bulk_global_factor_test.go, api/rest/confiant_test.go, api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/dpo_test.go, api/rest/factor_test.go, api/rest/floor_test.go, api/rest/global_factor_test.go, api/rest/pixalate_test.go, api/rest/publisher_domain_test.go, api/rest/publisher_new_test.go, api/rest/publisher_update_test.go, api/rest/rest_test.go, api/rest/targeting_test.go, api/rest/user_test.go, core/history.go, dto/history.go, modules/history/changes.go, modules/history/history.go
1. hided internal fields;
2. added demand_partner_name;
=> [3225] history changes

api/rest/rest_test.go, api/rest/search_test.go, core/search.go, dto/search.go, dto/search_test.go, migrations/022_search_view.up.sql
1. renaming search sections;
2. changing sections order;
=> [3092] renaming search sections, changing sections order

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/floor.go, cmd/api.go, core/bulk/bulk.go, core/bulk/core_test.go, core/bulk/factor_delete_test.go, core/bulk/floor.go, core/bulk/floor_delete_test.go
1. adding new API: /floor/delete" soft delete in floor table and remove rules in metadata_queue table
2. adding component test
3. fix small bug in old delete floor mechanism
4. adding new column in floor table
=> adding /floor/delete API

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, core/bid_caching.go, core/publisher.go, core/publisher_domain.go, core/refresh_cache.go
1. fixed duplication problem in Both
2. 0 value now appears in swagger
3. added bid and refresh data to publisher/get and domain/get
4. fixed some db issues with 2 tables 5.
=> Bid cache and refresh cache refactor:

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/rest_test.go, api/rest/targeting_test.go, core/targeting.go, core/targeting_test.go, dto/targeting.go, migrations/20241218122003_add_rule_id_to_js_targeting.sql, models/targeting.go, models/targeting_test.go, sqlboiler.toml
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3470)
1. Added `rule_id`;
2. Changed `price_model` in metadata to lower and without whitespaces;
3. Processing `daily_cap` in metadata if it doesn't set;
=> [3470] updated metadata for js targeting

utils/constant/constants.go, workers/sellers/adsTxt.go, workers/sellers/helpers.go, workers/sellers/seller-email.go, workers/sellers/sellers_test.go, workers/sellers/worker.go
- Fix ads txt - add timeout handling function
- Delete unused code
- Change ads txt url for inapp
- Add tests for url creating function
=> Fix sellers

utils/constant/constants.go
1. Change timeout for opening ads.txt file from 20 seconds to 1 minute
=> Change sellers ads.txt timeout

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, bcdb/filter/bool.go, core/demand_partner.go, dto/demand_partner.go, validations/demand_partner_validation.go, validations/demand_partner_validation_test.go, validations/validation.go, workers/dpo/worker.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3491)
- Add automation and threshold validations and tests
- Change automation filter to bool in dpo automation worker
=> Add automation values

api/rest/bid_caching.go, api/rest/bid_caching_test.go, api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/rest_test.go, core/bid_caching.go, dto/bid_caching.go, migrations/20250119140854_bid_cache_control_percentage.sql, models/bid_caching.go, models/bid_caching_test.go, models/dpo.go, validations/bid_caching_validation.go, validations/bid_caching_validation_test.go, validations/validation.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3501/)
1. Added `control_percentage` to bid caching;
2. Updated validations for bid caching;
=> 3501 NP - Cached creatives limit - add "Control Group%" setting to the cache rules

core/bulk/dpo.go, core/bulk/dpo_test.go, core/dpo_rule.go, dto/dpo_rule.go, workers/dpo/data.go
Fix issue with active flag, now when we are sending update or insert request via bulk/dpo it will set active:true
=> Fix dpo automation

cmd/api.go
temporary - until full demand partner management will be released
=> temporary turned off demand partner validation

api/rest/demand_partner_test.go, api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, dto/demand_partner.go, dto/demand_partner_test.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3539/)
=> 3539 added ads txt line and line name to demand partner connections, children and seat owner

api/rest/demand_partner_test.go, api/rest/rest.go, api/rest/rest_test.go, cmd/api.go, core/bulk/bulk.go, core/bulk/dpo.go, core/bulk/dpo_test.go, core/bulk/factor.go, core/bulk/factor_test.go, core/bulk/floor.go, core/bulk/global_factor.go, core/bulk/global_factor_test.go, core/bulk/metadata_queue.go, core/bulk/metadata_queue_test.go, core/bulk/publisher_demand.go, core/core.go, core/demand_partner.go, core/refresh_cache.go, modules/ads_txt/ads_txt.go, modules/ads_txt/line.go, modules/ads_txt/query.go, utils/constant/constants.go, workers/dpo/worker.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3522)
=> 3522 Updating ads.txt table according changes in demand partner

config/string_map.go, main.go, utils/helpers/formatter.go, workers/email_reports/helpers.go, workers/email_reports/looping_ratio_decrease_alert/data.go, workers/email_reports/looping_ratio_decrease_alert/worker.go, workers/email_reports/rpm_decrease/data.go, workers/email_reports/rpm_decrease/worker.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3154)
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/2685)
- Added $ and % to metrics
- Change const variables to metrics from worker cron
=> [3154] Changes in formatting data

.github/workflows/deploy.yml
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3582)
=> [3582] removed excess steps from deploy pipeline

api/rest/demand_partner_test.go, api/rest/rest_test.go, core/demand_partner.go, dto/demand_partner.go, dto/demand_partner_test.go, modules/ads_txt/query.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3614)
=> [3614] fix creating ads txt lines

api/rest/docs/docs.go, api/rest/docs/swagger.json, api/rest/docs/swagger.yaml, api/rest/publisher_create_test.go, api/rest/publisher_domain_test.go, api/rest/publisher_get_test.go, api/rest/publisher_update_test.go, api/rest/rest_test.go, core/publisher.go, core/publisher_domain.go, dto/publisher.go, dto/publisher_domain.go, migrations/20250402092539_is_direct_for_publishers_and_domains.sql, models/ads_txt_group_by_dp_view.go, models/ads_txt_main_view.go, models/publisher.go, models/publisher_domain.go, models/publisher_domain_test.go, models/publisher_test.go
[Task](https://dev.azure.com/onlinemediasolutions/HelpDesk/_workitems/edit/3638)
=> [3638] added is_direct for publishers and domains
